name: "Cats-bot"

services:

  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.database
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .env.bot

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - database


volumes:
  db_data:

